models.py
import time

from flask_login import UserMixin
from sqlalchemy import Column, Integer, String
from ext import db

def get_current_timestamp():
    return int(time.time())

class User(db.Model, UserMixin):
    id = Column(Integer, primary_key=True)
    email = Column(String, nullable=False, index=True, unique=True)
    password = Column(String, nullable=False)

    created_at = Column(default=get_current_timestamp)

    def __repr__(self):
        return f'<User {self.id}>'



class Link(db.Model):
    id = Column(Integer, primary_key=True)
    short_id = Column(String, nullable=False, index=True)
    long_url = Column(String, nullable=False)
    description = Column(String, nullable=True)
    views = Column(Integer, default=0)
    created_at = Column(default=get_current_timestamp)

    user_id = Column(Integer, db.ForeignKey(User.id), nullable=False)
    user = db.relationship(User, backref=db.backref('links', lazy=True))

    def __repr__(self):
        return f'<Link {self.id}>'

app.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from blueprints import admin_dashboard
from blueprints import main
import ext
import config
from models import User

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = config.SQLALCHEMY_DATABASE_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = config.SECRET_KEY

ext.db.init_app(app)
migrate = Migrate(app, ext.db)
login_manager = LoginManager()
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()

app.register_blueprint(admin_dashboard.app, url_prefix='/admin')
app.register_blueprint(main.app)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=8080)

blueprints/admin_dashboard.py
import random
import re, hashlib
import string
import threading

import qrcode
from flask import Blueprint, render_template, request, flash, redirect, url_for, send_file
from flask_login import login_user, login_required, current_user, logout_user

import config
import os
from ext import db
from models import User, Link

app = Blueprint('admin_dashboard', __name__)


@app.route('/')
@login_required
def index():
    return render_template('admin_dashboard/dashboard.html')


@app.route(config.ADMIN_LOGIN_ROUTE_URL, methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        return render_template('admin_dashboard/login.html')
    else:
        email = request.form.get('email')
        password = request.form.get('password')

        has_error = False

        if not re.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email):
            flash('لطفا ایمیل معتبر وارد کنید')
            has_error = True

        if len(password) < 8:
            flash('رمز عبور باید حداقل 8 کاراکتر باشد')
            has_error = True

        if has_error:
            return redirect(url_for('admin_dashboard.login'))

        user = User.query.filter(User.email == email).first()
        if user is None:
            if config.ADMIN_REGISTRATION_IS_ALLOWED is False:
                flash('ثبت نام ادمین جدید غیر فعال است')
                return redirect(url_for('admin_dashboard.login'))

            user = User(email=email)
            user.password = hashlib.sha256(password.encode('utf-8')).hexdigest()

            db.session.add(user)
            db.session.commit()

        else:
            if user.password != hashlib.sha256(password.encode('utf-8')).hexdigest():
                flash('رمز عبور اشتباه است')
                return redirect(url_for('admin_dashboard.login'))

        login_user(user, remember=True)

        return redirect(url_for('admin_dashboard.index'))


@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('admin_dashboard.login'))


@app.route('/shorten', methods=['POST'])
@login_required
def shorten():
    url = request.json.get('url')
    short_id = request.json.get('short_id')
    description = request.json.get('description')

    short_id = short_id.strip().lower()

    if short_id == "":
        short_id = ''.join(random.choices(string.ascii_letters + string.digits, k=4))
    else:
        if " " in short_id:
            return {'status': 'error', 'error': 'شناسه کوتاه نباید فاصله داشته باشد'}


    check_link = Link.query.filter(Link.short_id == short_id).first()
    if check_link is not None:
        return {'status': 'error', 'error': 'شناسه کوتاه تکراری است'}

    link = Link(short_id=short_id, long_url=url, description=description)
    link.user_id = current_user.id
    db.session.add(link)
    db.session.commit()

    return {'status': 'success', 'shortUrl': request.url_root + short_id}


@app.route('/delete/<link_id>', methods=['GET'])
@login_required
def delete_link(link_id):
    Link.query.filter(Link.id == link_id, Link.user_id == current_user.id).delete()
    db.session.commit()

    return redirect(url_for('admin_dashboard.index'))


@app.route('/download-qrcode/<link_id>', methods=['GET'])
@login_required
def download_qrcode(link_id):
    link = Link.query.filter(Link.id == link_id, Link.user_id == current_user.id).first_or_404()

    file_path = f'./tmp/{current_user.id}.{link.short_id}.png'
    os.makedirs("./tmp/", exist_ok=True)
    img = qrcode.make(request.url_root + link.short_id)
    img.save(file_path)

    # deleting image after 10 seconds
    def remove_file(file_path):
        if os.path.exists(file_path):
            os.remove(file_path)

    t = threading.Timer(10, remove_file, (file_path,))
    t.start()

    return send_file(file_path, mimetype='image/png', as_attachment=True)

blueprints/main.py
from flask import Blueprint, render_template, abort, redirect

import config
from ext import db
from models import Link

app = Blueprint('main', __name__)


@app.route('/')
def index():
    if config.MAIN_PAGE_REDIRECT_TO == "":
        abort(404)
    else:
        return redirect(config.MAIN_PAGE_REDIRECT_TO)


@app.route('/<short_id>')
def redirect_to_long_url(short_id):
    short_id = short_id.lower()

    link = Link.query.filter_by(short_id=short_id).first_or_404()
    link.views += 1
    db.session.commit()
    return render_template('main/redirect.html', long_url=link.long_url)

templates/admin_dashboard/dashboard.html
{% extends 'base.html' %}
{% block head %}
    <title>پنل مدیریت</title>
{% endblock %}

{% block body %}

    <div class="container mt-5" style="max-width: 500px;">
        <h1 class="text-center mb-4">کوتاه‌کننده لینک</h1>
        <form id="urlForm" class="mb-4">
            <div class="mb-3">
                <label for="longUrl" class="form-label">لینک بلند</label>
                <input type="url" class="form-control" id="longUrl" placeholder="لینک خود را وارد کنید" required>
            </div>
            <div class="mb-3">
                <label for="shortId" class="form-label">شناسه کوتاه</label>
                <input type="text" class="form-control" id="shortId" placeholder="کلمه مورد نظر را وارد کنید">
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">توضیحات</label>
                <textarea class="form-control" id="description" placeholder="توضیحات خود را وارد کنید"></textarea>
            </div>
            <div id="result" class="alert alert-primary d-none">
                <strong>لینک کوتاه‌شده:</strong> <a id="shortUrl" href="#" target="_blank"></a>
            </div>
            <div id="error" class="result alert alert-danger d-none"></div>
            <button type="submit" class="btn btn-primary w-100">کوتاه کردن لینک</button>
        </form>

        <a href="{{ url_for('admin_dashboard.logout') }}" class="btn btn-danger w-100">خروج از حساب کاربری
            ({{ current_user.email }})</a>
    </div>

    <div class="container mt-5 " style="max-width:500px;">
        <h1 class="text-center mb-4">لینک های ساخته شده</h1>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>توضیحات</th>
                    <th>لینک کوتاه</th>
                    <th>عملیات</th>
                </tr>
                </thead>
                <tbody>
                {% for link in current_user.links|reverse %}
                    <tr {% if loop.index % 2 == 0 %} class="table-active" {% endif %}>
                        <td class="small text-muted">
                            {{ link.description if link.description != none and link.description != "" else "-" }}
                        </td>
                        <td>
                            <a target="_blank"
                               href="{{ url_for('main.redirect_to_long_url', short_id=link.short_id) }}">{{ link.short_id }}</a>
                        </td>

                        <td>
                            <div class="d-flex">
                                <a href="javascript:copyToClipboard('{{ request.url_root }}{{ link.short_id }}')"
                                   class=" text-success btn p-0 mx-1 "
                                   data-bs-toggle="tooltip"
                                   data-bs-custom-class="green-tooltip" data-bs-placement="bottom"
                                   data-bs-title="کپی لینک کوتاه">
                                    <i class="bi bi-clipboard fs-6"></i>
                                </a>

                                <a href="javascript:deleteLink('{{ url_for('admin_dashboard.delete_link', link_id=link.id) }}')"
                                   class="text-decoration-none text-danger mx-1" data-bs-toggle="tooltip"
                                   data-bs-custom-class="red-tooltip" data-bs-placement="bottom"
                                   data-bs-title="حذف">
                                    <i class="bi bi-trash3 fs-6"></i>
                                </a>

                                <a href="{{ url_for('admin_dashboard.download_qrcode', link_id=link.id) }}"
                                   class="text-decoration-none mx-1" data-bs-toggle="tooltip"
                                   data-bs-custom-class="dark-blue-tooltip" data-bs-placement="bottom"
                                   data-bs-title="دانلود QRCode">
                                    <i class="bi bi-qr-code fs-6"></i>
                                </a>

                                <span data-bs-custom-class="blue-tooltip" data-bs-placement="bottom"
                                      data-bs-toggle="tooltip"
                                      data-bs-title="اطلاعات بیشتر">
                                <a class="text-decoration-none mx-1 text-info" data-bs-toggle="collapse"
                                   href="#linkCollapseData-{{ link.id }}"
                                   role="button"
                                   aria-expanded="false" aria-controls="linkCollapseData-{{ link.id }}">
                                    <i class="bi bi-info-circle fs-6"></i>
                                </a>
                                </span>

                            </div>
                        </td>
                    </tr>
                    <tr class="collapse " id="linkCollapseData-{{ link.id }}">
                        <td colspan="3">
                            <table class="table table-borderless table-sm ">
                                <thead>
                                <tr>
                                    <th class="small">لینک بلند</th>
                                    <th class="small">تعداد بازدید</th>
                                    <th class="small">تاریخ ایجاد</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td class="small"><a class="small"
                                                         href="{{ link.long_url }}">{{ link.long_url }}</a></td>
                                    <td class="small">{{ link.views }}</td>
                                    <td class="unixtime small">{{ link.created_at }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    <script>
        document.getElementById('urlForm').addEventListener('submit', async (e) => {
            e.preventDefault();

            const longUrl = document.getElementById('longUrl').value;
            const shortId = document.getElementById('shortId').value;
            const description = document.getElementById('description').value;
            const resultDiv = document.getElementById('result');
            const shortUrlLink = document.getElementById('shortUrl');
            const errorDiv = document.getElementById('error');

            try {
                const response = await fetch('{{ url_for("admin_dashboard.shorten") }}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    credentials: 'include',
                    body: JSON.stringify(
                        {
                            url: longUrl,
                            short_id: shortId,
                            description: description
                        }
                    ),
                });

                const data = await response.json();

                if (data.status === 'success') {
                    shortUrlLink.href = data.shortUrl;
                    shortUrlLink.textContent = data.shortUrl;
                    resultDiv.classList.remove('d-none');
                    errorDiv.classList.add('d-none');
                } else if (data.status === 'error') {
                    errorDiv.textContent = data.error;
                    errorDiv.classList.remove('d-none');
                    resultDiv.classList.add('d-none');
                }
            } catch (error) {
                errorDiv.textContent = error.message;
                errorDiv.classList.remove('d-none');
                resultDiv.classList.add('d-none');
            }
        });

        function copyToClipboard(text) {
            navigator.clipboard.writeText(text);
            alert(text + " کپی شد");
        }

        function deleteLink(link) {
            if (confirm("آیا از حذف این لینک مطمئن هستید؟")) {
                window.location.href = link
            }
        }
    </script>

{% endblock %}

templates/admin_dashboard/login.html
{% extends 'base.html' %}
{% block head %}
    <title>ورود به پنل مدیریت</title>
{% endblock %}

{% block body %}

    <div class="container d-flex align-items-center justify-content-center min-vh-100">
        <div class="card shadow-sm p-4" style="max-width: 400px; width: 100%;">
            <h4 class="mb-4 text-center">ورود/ثبت نام حساب کاربری</h4>
            <form action="#" method="post">

                <div class="mb-3">
                    <label for="email" class="form-label">ایمیل</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="ایمیل را وارد کنید">
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">رمز عبور</label>
                    <input type="password" class="form-control" id="password" name="password"
                           placeholder="رمز عبور را وارد کنید">
                </div>


                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% endwith %}


                <button type="submit" class="btn btn-primary w-100">ورود/ثبت نام</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="fa" dir="rtl" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{{ url_for('static',filename='bootstrap/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='bootstrap/bootstrap-icons/bootstrap-icons.min.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='styles/index.css') }}">

    {% block head %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}

<script src="{{ url_for('static',filename='bootstrap/bootstrap.bundle.min.js') }}"></script>
<script>
    document.querySelectorAll('.unixtime').forEach((element) => {

        const fmt = new Intl.DateTimeFormat('fa-IR', {
            dateStyle: 'short', timeStyle: 'short', calendar: 'persian'
        });
        element.textContent = fmt.format(element.textContent * 1000);

    });

    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

</script>
</body>
</html>

templates/main/redirect.html
{% extends 'base.html' %}
{% block head %}
    <title>در حال انتقال...</title>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
{% endblock %}

{% block body %}
    <div class="d-flex flex-column justify-content-center align-items-center vh-100 vw-100">

        <div class="d-flex flex-column justify-content-center align-items-center"
             style="max-width: 500px;min-width: 300px">
            <h3 class="mb-3">در حال انتقال...</h3>
            <div class="progress w-100">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary"
                     style="width: 100%"></div>
            </div>
        </div>

    </div>

    <script>
        setTimeout(() => {
            window.location.href = '{{ long_url }}';
        }, 100);
    </script>

{% endblock %}